FROM python:3.11-slim

WORKDIR /app

COPY ./course_service /app
COPY ./common /app/common

RUN pip install --no-cache-dir -r /app/requirements.txt

ENV PYTHONPATH="/app/common:${PYTHONPATH}"

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
